# Generated by Django 2.2.17 on 2021-01-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_conditionaloffer_combinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionaloffer',
            name='offer_type',
            field=models.CharField(choices=[('Site', 'Site offer - available to all users'), ('Voucher', 'Voucher offer - only available after entering the appropriate voucher code'), ('User', 'User offer - available to certain types of user'), ('Session', 'Session offer - temporary offer, available for a user for the duration of their session')], max_length=128, verbose_name='Type'),
        ),
    ]
