# Generated by Django 2.2.17 on 2021-01-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_auto_20200801_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherset',
            name='offer',
        ),
    ]
